#!/usr/bin/env bash

set -eu -o pipefail

SCRIPT_PATH=$(dirname "$(readlink -f "$0")")

export DNS_UPDATER_PATH="$(realpath ${SCRIPT_PATH}/../update-dns)"
export DNS_UPDATER_ENVFILE="$(realpath ${SCRIPT_PATH}/../prod.env)"

echo "Expanded unit file:"
cat "${SCRIPT_PATH}"/dns-updater.service | envsubst | sudo tee /etc/systemd/system/dns-updater.service

echo -e "\nExpanded timer file:"
cat "${SCRIPT_PATH}"/dns-updater.timer | envsubst | sudo tee /etc/systemd/system/dns-updater.timer
